apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: inkwell-dev
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/cpu-throttling: 'true'
        run.googleapis.com/memory: '512Mi'
        run.googleapis.com/cpu: '1000m'
        run.googleapis.com/max-scale: '10'
        run.googleapis.com/min-scale: '0'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: inkwell-bucket@inkwell-447220.iam.gserviceaccount.com
      containers:
        - image: europe-west10-docker.pkg.dev/inkwell-447220/inkwell-repo/inkwell-dev:latest
          ports:
            - name: http1
              containerPort: 8080
          env:
            - name: NODE_ENV
              value: production
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: inkwell-secrets
                  key: jwt-secret
            - name: JWT_REFRESH_SECRET
              valueFrom:
                secretKeyRef:
                  name: inkwell-secrets
                  key: jwt-refresh-secret
            - name: DB_URI
              valueFrom:
                secretKeyRef:
                  name: inkwell-secrets
                  key: db-uri
            - name: SALT
              valueFrom:
                secretKeyRef:
                  name: inkwell-secrets
                  key: salt
            - name: INKWELL_GOOGLE_STORAGE_BUCKET
              valueFrom:
                secretKeyRef:
                  name: inkwell-secrets
                  key: storage-bucket
          # Add other environment variables as needed
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
          startupProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 30
            failureThreshold: 3
