steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'europe-west10-docker.pkg.dev/$PROJECT_ID/inkwell-repo/inkwell-dev:$COMMIT_SHA',
        '-t',
        'europe-west10-docker.pkg.dev/$PROJECT_ID/inkwell-repo/inkwell-dev:latest',
        '.',
      ]

  # Create Artifact Registry repository (if it doesn't exist)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'artifacts',
        'repositories',
        'create',
        'inkwell-repo',
        '--repository-format=docker',
        '--location=europe-west10',
        '--project=$PROJECT_ID',
      ]
    # Allow this step to fail if repository already exists
    id: 'create-repo'
    allowFailure: true

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west10-docker.pkg.dev/$PROJECT_ID/inkwell-repo/inkwell-dev:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west10-docker.pkg.dev/$PROJECT_ID/inkwell-repo/inkwell-dev:latest']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        'inkwell-dev',
        '--image',
        'europe-west10-docker.pkg.dev/$PROJECT_ID/inkwell-repo/inkwell-dev:$COMMIT_SHA',
        '--region',
        'europe-west10',
        '--platform',
        'managed',
        '--allow-unauthenticated',
        '--memory',
        '512Mi',
        '--cpu',
        '1000m',
        '--max-instances',
        '10',
        '--min-instances',
        '0',
        '--port',
        '8080',
        '--timeout',
        '300s',
        '--concurrency',
        '80',
        '--set-env-vars',
        'NODE_ENV=production',
        '--set-secrets',
        'JWT_SECRET=inkwell-jwt-secret:latest',
        '--set-secrets',
        'JWT_REFRESH_SECRET=inkwell-jwt-refresh-secret:latest',
        '--set-secrets',
        'DB_URI=inkwell-db-uri:latest',
        '--set-secrets',
        'SALT=inkwell-salt:latest',
        '--set-secrets',
        'INKWELL_GOOGLE_STORAGE_BUCKET=inkwell-storage-bucket:latest',
      ]

# Store images in Artifact Registry
images:
  - 'europe-west10-docker.pkg.dev/$PROJECT_ID/inkwell-repo/inkwell-dev:$COMMIT_SHA'
  - 'europe-west10-docker.pkg.dev/$PROJECT_ID/inkwell-repo/inkwell-dev:latest'

# Build configuration
options:
  # Use high CPU machines for faster builds
  machineType: 'E2_HIGHCPU_8'
  # Use a larger disk for Docker builds
  diskSizeGb: 100
  # Enable logging
  logging: CLOUD_LOGGING_ONLY

# Build timeout (default is 10 minutes)
timeout: '1200s'
