name: Deploy to AWS Elastic Beanstalk (dev)

on:
  push:
    branches: [ main ]

env:
  AWS_REGION: eu-central-1 
  EB_ENVIRONMENT_NAME: Inkwell-server-env
  EB_APPLICATION_NAME: inkwell-server
  EB_DEPLOYMENT_PACKAGE: deploy.zip

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev  

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Build Application
        run: yarn run build

      - name: Generate Deployment Package
        run: |
          zip -r ${{ env.EB_DEPLOYMENT_PACKAGE }} ./build package.json yarn.lock .ebextensions .platform node_modules
          ls -lh ${{ env.EB_DEPLOYMENT_PACKAGE }} 

      # Set the version label before deployment
      - name: Set Version Label
        id: set_version_label
        run: |
          VERSION_LABEL="ver-${{ github.run_number }}-${{ github.sha }}"
          echo "VERSION_LABEL=$VERSION_LABEL" >> $GITHUB_ENV
          echo "Version label set to $VERSION_LABEL"

      - name: Debug Version Label
        run: |
          echo "Version Label is: ${{ env.VERSION_LABEL }}"

      # Add these steps before Deploy to EB
      - name: Delete Existing Version (If Exists)
        continue-on-error: true
        run: |
          aws elasticbeanstalk delete-application-version \
            --application-name ${{ env.EB_APPLICATION_NAME }} \
            --version-label "ver-${{ github.run_number }}-${{ github.sha }}" \
            --region ${{ env.AWS_REGION }} \
            --delete-source-bundle || true

      - name: Upload to S3
        run: |
          aws s3 cp ${{ env.EB_DEPLOYMENT_PACKAGE }} s3://elasticbeanstalk-deployments-inkwell/inkwell-server/${{ env.EB_DEPLOYMENT_PACKAGE }}

      - name: Create Application Version
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name ${{ env.EB_APPLICATION_NAME }} \
            --version-label "ver-${{ github.run_number }}-${{ github.sha }}" \
            --source-bundle S3Bucket="elasticbeanstalk-deployments-inkwell",S3Key="inkwell-server/${{ env.EB_DEPLOYMENT_PACKAGE }}" \
            --region ${{ env.AWS_REGION }}

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ env.EB_APPLICATION_NAME }}
          environment_name: ${{ env.EB_ENVIRONMENT_NAME }}
          version_label: "ver-${{ github.run_number }}-${{ github.sha }}" 
          region: ${{ env.AWS_REGION }}
          file: ${{ env.EB_DEPLOYMENT_PACKAGE }}
          wait_for_deployment: true 
          existing_bucket_name: "elasticbeanstalk-deployments-inkwell"
