name: Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: development
      url: ${{ vars.BASE_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js (if needed)
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Authenticate Railway CLI
        run: railway login --apiKey "$RAILWAY_TOKEN"
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
